repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.5.0
        hooks:
        -   id: trailing-whitespace
        -   id: check-added-large-files
    -   repo: https://github.com/golangci/golangci-lint
        rev: master
        hooks:
        -   id: golangci-lint